apiVersion: v1
kind: Namespace
metadata:
  name: burgers
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: burgerback-deployment
  namespace: burgers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: burgerback
  template:
    metadata:
      labels:
        app: burgerback
        version: 1053df9f627c16135278714f5c5bf25515da0094
    spec:
      containers:
      - name: burgerback
        image: scottloft/burger-back:1053df9f627c16135278714f5c5bf25515da0094
        resources: 
          requests:
            memory: "100Mi"
          limits:
            memory: "200Mi"
        ports:
        - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: burgerfront-deployment
  namespace: burgers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: burgerfront
  template: 
    metadata:
      labels:
        app: burgerfront
        version: 1053df9f627c16135278714f5c5bf25515da0094
    spec:
      containers:
      - name: burgerfront
        image: scottloft/burger-front:1053df9f627c16135278714f5c5bf25515da0094
        ports:
        - containerPort: 3000
        env:
        - name: BACKEND
          value: http://burgerback:5000
---
apiVersion: v1
kind: Service
metadata:
  name: burgerback
  namespace: burgers
spec:
  selector:
    app: burgerback
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: burgerfront
  namespace: burgers
spec:
  selector:
    app: burgerfront
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: burgerfront
  namespace: burgers
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    name: burgerfront
  annotations:
spec:
  ingressClassName: nginx
  rules:
  - host: pr12.vclusterbox.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: burgerfront
            port:
              number: 3000 